### ISSUE TITLE
StckUtils

### ISSUE THREAD

**Issue by Elaiterfun** [StckOverflw/StckUtils#8]
Hi Plugin Creator,
I've got a question how I install your plugin. Where can I download the Paper Api? I want the Plugin, because I want to play the XpBorder Challenge but the Plugin doesn't works. Pls can you help.
Best Regards,
Elaiterfun

**Comment by l4zs** [comment]
Hey, 
in order to use the plugin overall you need to use a [paper](https://papermc.io/) based server software and the Minecraft Version 1.17.1.
To play the LevelBorder Challenge you also need to install another plugin called [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/).
